import os
import sys
import asyncio
from dotenv import load_dotenv

load_dotenv(override=True)

from app.services.spam_rag_service import get_spam_rag_service

def test_search():
    service = get_spam_rag_service()
    
    # We use the intent summary string as if it was generated by the LLM
    query_intent = "Fraud Accusation / Bypassing spam filters using decomposed characters / Warning that persistent loss of contact is evidence of a scam."
    
    print(f"Searching for intent: {query_intent}")
    results = service.search_similar(query_intent, k=5)
    
    print(f"\nMetric: {results.get('metric')}")
    print(f"Stats: {results.get('stats')}")
    
    for i, hit in enumerate(results.get("hits", [])):
        dist = hit.get("distance", 999.0)
        print(f"[{i}] Distance: {dist:.4f} | Original: {hit.get('message', '')[:60]}")

if __name__ == "__main__":
    test_search()
